services:
    server:
        user: '$DUID:$DGID'
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        image: dev_tablet_server
        container_name: dev_tablet_server
        restart: unless-stopped
        env_file: server/.env.dev
        volumes:
            - ./server:/var/www
        ports:
            - "3000:3000"
        depends_on:
            - ytapi

    ytapi:
        user: '$DUID:$DGID'
        build:
            context: ./ytapi
            dockerfile: Dockerfile
        image: dev_tablet_ytapi
        container_name: dev_tablet_ytapi
        restart: unless-stopped
        environment:
            - PYTHONUNBUFFERED=True
        volumes:
            - ./ytapi:/ytapi
            - ./server/storage/stops:/stops
        command: python3 ./main.py
        depends_on:
            - ytproxy

    ytproxy:
        build:
            context: ./ytproxy
            dockerfile: Dockerfile
        image: dev_tablet_ytproxy
        container_name: dev_tablet_ytproxy
        restart: unless-stopped
        environment:
            - PYTHONUNBUFFERED=True
        command: ./transport_proxy.py --port 3002 --delay 10 --verbose 4
